### ISSUE TITLE
Links provided in `sfingev2_download.bash` are not working

### ISSUE THREAD

**Issue by alkarnjn** [tim-rohwedder/fixed-length-fingerprint-extractors#1]
Hi,

The links provided for SFinGe dataset download is showing a 404 error.
Please see the image below:
![image](https://github.com/tim-rohwedder/fixed-length-fingerprint-extractors/assets/119038680/02e039a8-94eb-4aa9-9d1d-3caa9603f3c3)

On another note: 
Can the pre-trained model also be provided/linked in the repository?

**Comment by tim-rohwedder** [comment]
Hello,

the bash script was meant for use within the working group at my university. Sharing all the data publically is not possible, due to NDA I signed with the university and partner universities.

If you want to use the SFinge images I can ask if the license allows sharing them (the data belongs to the university). Regarding the pre-trained model it should be possible to share, but again I need to ask the leading professor at the working group.

It might take a few days until I get a response and it would be good to know your affiliation (university or company) and how you intend to use the model and data in order to get permission from the university. Please write me a mail with that information and if I am allowed, I will send you the download links.

My email is tim.rohwedder@stud.h-da.de

**Comment by tim-rohwedder** [comment]
I will remove the bash script to avoid confusion in the future.
