### ISSUE TITLE
Does this model require alignment on challenging datasets?

### ISSUE THREAD

**Issue by TDNAI** [tim-rohwedder/fixed-length-fingerprint-extractors#6]
Thanks for the great implementation but please For instance consider if the dataset includes cases where the fingers are not centred or are in various poses, does this repository provide an algorithm or capability to handle such scenarios? If not, could you recommend a library that addresses these issues? I tested the default dataset, and it was relatively straightforward (e.g., centre-cropped images, etc.). Thanks in advanced

Tested it on this dataset:

https://datadryad.org/stash/dataset/doi:10.5061/dryad.612jm649q

```
Equal-Error-Rate: 0.091
```

FVC2002:

```
Equal-Error-Rate: 0.2921875
```

I believe that, based on the evaluations, proper alignment is necessary, and this does not seem to be a self-contained method for fingerprint recognition. Could you please clarify or provide guidance if I am misunderstanding or doing something incorrectly?

**Comment by tim-rohwedder** [comment]
Hello TDNAI,

I assume, that it is necessary to at least fine-tune the model in order to work properly on the FVC datasets. They are quite different from the MCYT dataset and also the synthetic data that was used for training.

Poor alignment has a negative effect, as shown in the BIOSIG paper. The original DeepPrint architecture had a pre-alignment module specifically to tackle poorly aligned data (it is also implemented in the repo but I got worse performance when I used it, so I have no trained weights for it).

But I think the different sensor types used in FVC might also contribute to the bad performance.
You try to play around with the preprocessing parameters (especially binarization with Gabor filtering). Maybe this can increase the performance and it requires very little effort compared to retraining any parts of the network.

Hope that was helpful,
Best regards Tim
